@startuml
'https://plantuml.com/sequence-diagram

class Loc_Node_Edge
{
    * Location (Class)
    * Node (Class)
}

interface GraphInterface
{

}

class DiGraph
{

}

interface GraphAlgoInterface
{

}

class GraphAlgo
{

}

class Agent
{

}

class Pokemon
{

}

class MyGame
{

}

class client
{

}

class student_code
{

}

Loc_Node_Edge --|> DiGraph
GraphAlgoInterface ..|> GraphAlgo
GraphInterface ..|> DiGraph
DiGraph --|> GraphAlgo

@enduml
@enduml