@startuml
'https://plantuml.com/sequence-diagram

class Loc_Node_Edge
{
    * Location (Class)
    * Node (Class)
}

interface GraphInterface
{

}

class DiGraph
{

}

class GraphAlgo
{

}

class Agent
{

}

class Pokemon
{

}

class Model
{

}

class Control
{

}

class GUI
{

}

class client
{

}

Loc_Node_Edge --|> DiGraph
GraphInterface ..|> DiGraph
DiGraph --|> GraphAlgo

DiGraph --|> GUI

Loc_Node_Edge --|> Pokemon
Loc_Node_Edge --|> Agent

Pokemon --|> Agent
Agent --|> Pokemon

GraphAlgo --|> Model
GraphAlgo --|> Control

Pokemon --|> Control
Agent --|> Control
Control --|> GUI
Control --|> Model
client --|> Control
@enduml
@enduml